### ISSUE TITLE
compile errors

### ISSUE THREAD

**Issue by hvr** [axman6/amazonka-s3-streaming#3]
Fyi, both the matrix builder (GHC 8.0 & 7.10) & Hackage's doc-builder (GHC 8.0) failed to build amazonka-s3-streaming:

- https://hackage.haskell.org/package/amazonka-s3-streaming-0.1.0.1/reports/
- https://hackage.haskell.org/package/amazonka-s3-streaming-0.1.0.0/reports/

I haven't investigated yet further

**Comment by axman6** [comment]
Thanks @hvr, I noticed this too and initially was really confused because it was compiling locally with what should've been a very similar environment. Seems that an API breaking change made it into v1.4.4 of  amazonka which removed a parameter from the `newEnv` function from Network.AWS. @brendanhay was this supposed to happen? The docs for even say this change is Since 1.5.0.

I'll upload a fix shortly.

**Comment by axman6** [comment]
Ok, this all seems to be sorted now, I've set up travis to help ensure this doesn't happen again, and the package is now building on everything from GHC 7.8.4 to 8.0.1, and only failing on HEAD, seemingly due to some issues in the `parallel` package.
